import { NamedNode, Prefixes } from 'n3';

const prefixes: Prefixes = {
    'owl': new NamedNode('http://www.w3.org/2002/07/owl#'),
    'rdf': new NamedNode('http://www.w3.org/1999/02/22-rdf-syntax-ns#'),
    'rdfs': new NamedNode('http://www.w3.org/2000/01/rdf-schema#'),
    'xsd': new NamedNode('http://www.w3.org/2001/XMLSchema#'),
    'sh': new NamedNode('http://www.w3.org/ns/shacl#'),
    'schema': new NamedNode('http://schema.org/'),
    'foaf': new NamedNode('http://xmlns.com/foaf/0.1/'),
    'dcterms': new NamedNode('http://purl.org/dc/terms/'),
    'dc': new NamedNode('http://purl.org/dc/elements/1.1/'),
    'skos': new NamedNode('http://www.w3.org/2004/02/skos/core#'),
    'void': new NamedNode('http://rdfs.org/ns/void#'),
    'prov': new NamedNode('http://www.w3.org/ns/prov#'),
    'geo': new NamedNode('http://www.w3.org/2003/01/geo/wgs#'),
    'geosparql': new NamedNode('http://www.opengis.net/ont/geosparql#'),
    'bibo': new NamedNode('http://purl.org/ontology/bibo#'),
    'dcat': new NamedNode('http://www.w3.org/ns/dcat#'),
    'qb': new NamedNode('http://purl.org/linked-data/cube#'),
    'vcard': new NamedNode('http://www.w3.org/2006/vcard/ns#'),
    'doap': new NamedNode('http://usefulinc.com/ns/doap#'),
    'gr': new NamedNode('http://purl.org/goodrelations/v1#'),
    'sio': new NamedNode('http://semanticscience.org/resource/'),
    'bio': new NamedNode('http://purl.org/vocab/bio/0.1/'),
    'mo': new NamedNode('http://purl.org/ontology/mo/'),
    'event': new NamedNode('http://purl.org/NET/c4dm/event.owl#'),
    'org': new NamedNode('http://www.w3.org/ns/org#'),
    'cnt': new NamedNode('http://www.w3.org/2008/content#'),
    'oa': new NamedNode('http://www.w3.org/ns/oa#'),
    'time': new NamedNode('http://www.w3.org/2006/time#'),
    'cc': new NamedNode('http://creativecommons.org/ns#'),
    'wgs84': new NamedNode('http://www.w3.org/2003/01/geo/wgs84_pos#'),
    'earl': new NamedNode('http://www.w3.org/ns/earl#'),
    'sioc': new NamedNode('http://rdfs.org/sioc/ns#'),
    'skosxl': new NamedNode('http://www.w3.org/2008/05/skos-xl#'),
    'vann': new NamedNode('http://purl.org/vocab/vann/'),
    'adms': new NamedNode('http://www.w3.org/ns/adms#'),
    'locn': new NamedNode('http://www.w3.org/ns/locn#'),
    'lode': new NamedNode('http://linkedevents.org/ontology/'),
    'frbr': new NamedNode('http://purl.org/vocab/frbr/core#'),
    'dcam': new NamedNode('http://purl.org/dc/dcam/'),
    'dctype': new NamedNode('http://purl.org/dc/dcmitype/'),
    'xhv': new NamedNode('http://www.w3.org/1999/xhtml/vocab#'),
    'rdfa': new NamedNode('http://www.w3.org/ns/rdfa#')
};

export { prefixes };